--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daniell/Imagens/Wallpapers/rrbltiehz7b31.png"

-- Special
background="#1c1c1c"
foreground="#e2cbc6"
cursor="#e2cbc6"

-- Colors
color0="#1c1c1c"
color1="#6b55eb"
color2="#eb55eb"
color3="#7861ec"
color4="#ec636b"
color5="#ed696b"
color6="#f1938f"
color7="#e2cbc6"
color8="#9e8e8a"
color9="#6b55eb"
color10="#eb55eb"
color11="#7861ec"
color12="#ec636b"
color13="#ed696b"
color14="#f1938f"
color15="#e2cbc6"
