# Shell variables
# Generated by 'wal'
wallpaper='/home/daniell/Imagens/Wallpapers/rrbltiehz7b31.png'

# Special
background='#1c1c1c'
foreground='#e2cbc6'
cursor='#e2cbc6'

# Colors
color0='#1c1c1c'
color1='#6b55eb'
color2='#eb55eb'
color3='#7861ec'
color4='#ec636b'
color5='#ed696b'
color6='#f1938f'
color7='#e2cbc6'
color8='#9e8e8a'
color9='#6b55eb'
color10='#eb55eb'
color11='#7861ec'
color12='#ec636b'
color13='#ed696b'
color14='#f1938f'
color15='#e2cbc6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
